set number
set autoindent
set expandtab
set shiftround
set shiftwidth=4
set tabstop=4
set hlsearch
set ignorecase
set incsearch
set smartcase
set linebreak
syntax enable
set wrap
set laststatus=2
set ruler
set wildmenu
set cursorline
set relativenumber
set noerrorbells
set title
set background=dark
set backspace=2