#!/usr/bin/env sh
yabai -m signal -add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

# bar settings
# yabai -m config status_bar                   off
# yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
# yabai -m config status_bar_background_color  0xff202020
# yabai -m config status_bar_foreground_color  0xffa8a8a8
# yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
# yabai -m config status_bar_power_icon_strip
# yabai -m config status_bar_space_icon        
# yabai -m config status_bar_clock_icon

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          2

yabai -m config active_window_border_color   0xff5fb8ff
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xff5fb8ff


yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

yabai -m rule --add app="^CopyQ$" manage=off


yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Pixelmator$" manage=off
yabai -m rule --add app="^Mullvad$" manage=off
echo "yabai configuration loaded.."

